MCQs :
-------
1.What is the output of the following program
public class ExceptionHandling 
{
	static void nit(int marks) 
	{
		if(marks<0||marks>50)
		{
			throw new IllegalArgumentException(Integer.toString(marks));
		}
	}
	public static void main(String[] args) {
		nit(55);
	}
}

==> Exception in thread "main" java.lang.IllegalArgumentException: 55

2.What is the output of the following program
class InvalidPassword extends Exception
{
	InvalidPassword(String str) {
		super(str);
	}
}

public class ExceptionHandling 
{
	static void nit(String password) throws InvalidPassword
	{
		if(password.length()<5)
			throw new InvalidPassword("Invalid Password");
		else 
		{
			System.out.println("Valid Password");
		}
	}
	public static void main(String[] args) {
		try {
			nit("NareshIT");
		} catch (InvalidPassword e) {
			System.out.println("Exception "+e);
		}
		
	}
}

==> Valid Password

3.What is the output of the following program
public class ExceptionHandling {
	public static void main (String[] args) {
		int a=20;
		for(int i=0;i<a;i++)
		   try{
		     System.out.println(a/i);  
		   }
	}
}

==> Exception beacause if we write try block then catch or finally block must be written its a compulsory.
	
	after writing the finally block it throw exception arthamatic exception casue : / by zero.
	
	after writing the catch block 
	output=java.lang.ArithmeticException: / by zero
20
10
6
5
4
3
2
2
2
2
1
1
1
1
1
1
1
1
1

4.What is the output of the following program
class Age extends Exception
{
	Age(String str) {
		super(str);
	}
}
public class ExceptionHandling 
{
	static void nit(int age) throws Age
	{
		if(age<18)
			throw new Age("Not for Vote");
		else 
		{
			System.out.println("Vote");
		}
	}
	public static void main(String[] args) {
		try {
			nit(15);
		} catch (Age e) {
			System.out.println("Exception "+e);
		}		
	}
}

==>  Not for Vote

5.What is the output of the following program
class Age extends Exception
{
	
}

public class ExceptionHandling 
{
	public static void main(String[] args) {
		try {
			throw new Age();
		} catch (Age e) {
			System.out.println("Exception "+e.getMessage());
		}
		
	}
}


6.What is the output of the following program
class Age extends Exception
{
	Age(String str) {
		super(str);
	}
}
public class ExceptionHandling 
{
	static void nit(int age) throws Age
	{
		if(age<18)
			throw new Age("Not for Vote");
		else 
		{
			System.out.println("Vote");
		}
	}
	public static void main(String[] args) {
		try {
			nit(19);
		} catch (Age e) {
			System.out.println("Exception "+e);
		}finally {
			System.out.println("Vote count");
		}
	}
}

7.What is the output of the following program
class Student{    
	void message()throws ArithmeticException {  //line 1
		System.out.println("Hai Student");  
		}    
	}    
class Faculty extends Student{    
	void message()throws Exception {  // line 2
		System.out.println("hai faculty");  
		}
}
public class ExceptionHandling 
{
	public static void main(String args[]) {    
	   Student nit = new Faculty();    
	     
	   try {    
	   nit.message();    
	   }  
	   catch (Exception e){}   
	  
	  }    
}     

8.What is the output of the following program
class Student{    
	void message(){  // line 1
		System.out.println("Hai Student");  
		}    
	}    
	    
class Faculty extends Student{    
	void message()throws Exception {  // line 2
		System.out.println("hai faculty");  
		}
}

public class ExceptionHandling 
{
	public static void main(String args[]) {    
	   Student nit = new Faculty();    
	     
	   try {    
	   nit.message();    
	   }  
	   catch (Exception e){}   
	  
	  }    
}

9.What is the output of the following program
class Student{    
	void message(){  //line 1
		System.out.println("Hai Student");  
		}    
	}    
	    
class Faculty extends Student{    
	void message()throws ArithmeticException {  // line 2
		System.out.println("hai faculty");  
		}
}
public class ExceptionHandling 
{
	public static void main(String args[]) {    
	   Student nit = new Faculty();    
	     
	   try {    
	   nit.message();    
	   }  
	   catch (Exception e){
}   
	 
	  }    
}

10.What is the output of the following program
class Student{    
	void message() throws Exception{  // line 1
		System.out.println("Hai Student");  
		}    
	}    
class Faculty extends Student{    
	void message()throws Exception {  // line 2
		System.out.println("hai faculty");  
		}
}

public class ExceptionHandling 
{
	public static void main(String args[]) {    
	   Student nit = new Faculty();    
	     
	   try {    
	   nit.message();    
	   }  
	   catch (Exception e){}   
	  
	  }    
}

-----------------------------------------------------------------------------
